require("core.options")
require("core.keymaps")
require("core.plugins")
require("core.autocmd")

require("plugins.colorscheme")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.oil")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.comment")
require("plugins.diagnostics")
require("plugins.undotree")
require("plugins.remote")
require("plugins.alpha")
require("plugins.opencode")
