require("core.options")
require("core.keymaps")
require("core.plugins")
require("core.autocmd")

require("config.colorscheme")
require("config.telescope")
require("config.treesitter")
require("config.oil")
require("config.cmp")
require("config.lsp")
require("config.comment")
require("config.diagnostics")
require("config.undotree")
require("config.remote")
